FROM node:20.17.0-alpine

WORKDIR /orders_service

COPY . .

RUN npm install --production

ARG ORDERS_SERVICE_PORT
ARG ORDERS_DB_SERVICE_NAME

ENV ORDERS_SERVICE_PORT=${ORDERS_SERVICE_PORT} ORDERS_DB_SERVICE_NAME=${ORDERS_DB_SERVICE_NAME}

EXPOSE ${ORDERS_SERVICE_PORT}

CMD [ "npm", "start" ]